# Basic Tensor Operations - 基础操作

Basic tensor operations using TensorFlow v2.
使用TensorFlow v2的基本操作。

- Author: Aymeric Damien
- Project: https://github.com/aymericdamien/TensorFlow-Examples/

In [8]:
from __future__ import print_function
import tensorflow as tf

In [9]:
# Define tensor constants. - 定义张量常量。
a = tf.constant(2)
b = tf.constant(3)
c = tf.constant(5)

In [10]:
# Various tensor operations. - 不同的张量基本运算操作。
# Note: Tensors also support python operators (+, *, ...) -张量也支持Python运算符（+，*，...）。
add = tf.add(a, b)
sub = tf.subtract(a, b)
mul = tf.multiply(a, b)
div = tf.divide(a, b)

# Access tensors value. - 转化为Numpy数组,并打印。
print("add =", add.numpy())
print("sub =", sub.numpy())
print("mul =", mul.numpy())
print("div =", div.numpy())

add = 5
sub = -1
mul = 6
div = 0.6666666666666666


In [11]:
# Some more operations. - 其他操作。 
mean = tf.reduce_mean([a, b, c]) # 求平均值的操作。
sum = tf.reduce_sum([a, b, c]) # 求和的操作。

# Access tensors value. - 转化为Numpy数组,并打印。
print("mean =", mean.numpy())
print("sum =", sum.numpy())

mean = 3
sum = 10


In [12]:
# Matrix multiplications. - 矩阵乘法。
matrix1 = tf.constant([[1., 2.], [3., 4.]])
matrix2 = tf.constant([[5., 6.], [7., 8.]])

product = tf.matmul(matrix1, matrix2)

In [13]:
# Display Tensor. - 显示张量。
product

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[19., 22.],
       [43., 50.]], dtype=float32)>

In [14]:
# Convert Tensor to Numpy. - 转化为Numpy数组。
product.numpy()

array([[19., 22.],
       [43., 50.]], dtype=float32)